const SET_INIT_TODOS: string = "SET_INIT_TODOS";
const SET_INIT_COMP_TODOS: string = "SET_INIT_COMP_TODOS";
const SET_TODOS: string = "SET_TODOS";
const SET_TODOS_COMPLETE: string = "SET_TODOS_COMPLETE";
const SET_COMP_TODOS: string = "SET_COMP_TODOS";
const DELETE_TODOS: string = "DELETE_TODOS";
const DELETE_COMP_TODOS: string = "DELETE_COMP_TODOS";

export {
  SET_INIT_TODOS,
  SET_INIT_COMP_TODOS,
  SET_TODOS,
  SET_TODOS_COMPLETE,
  SET_COMP_TODOS,
  DELETE_TODOS,
  DELETE_COMP_TODOS,
};
